spring.application.name=freshmart-order-management
server.port=8080
spring.thymeleaf.cache=false
app.data.users=data/users.txt
app.data.products=data/products.txt
app.data.orders=data/orders.txt
app.data.carts=data/carts.txt
